<?php
/**
 * The core plugin class that is used to define internationalization,
 * dashboard-specific hooks, and public-facing site hooks.
 * 
 * @author arstropica
 *
 */
class GF_TenStreet {

    /**
     * Admin Page Hook
     *
     * Generated by 'add_menu_page' function.
     *
     * @var string
     */
    private $page_hook;
    
    /**
     * Admin Class
     *
     * Generated by 'init_GF_TenStreet' method.
     *
     * @var object
     */
    private $admin_gf_tenstreet;
    
    /**
     * GravityForm Addon Class
     *
     * Generated by 'init_GF_TenStreet' method.
     *
     * @var object
     */
    private $addon_gf_tenstreet;
    
    /**
     * TenStreet Log Custom Post Type Class
     *
     * Generated by 'init_GF_TenStreet' method.
     *
     * @var object
     */
    private $post_type;
    
    /**
     * Plugin Dir Absolute Path
     *
     * @var string
     */
    protected static $plugin_path;
    
    /**
     * Plugin File Absolute Path
     *
     * @var string
     */
    protected static $plugin_file;
    
    /**
     * TenStreet API Endpoints
     * 
     * @var array
     */
    protected static $wsdl = [
        'DEV' => 'https://devdashboard.tenstreet.com/post/',
        'PROD' => 'https://dashboard.tenstreet.com/post/'
    ];
    
    /**
     * TenStreet Service Name
     * 
     * @var string
     */
    protected static $service_name = 'subject_upload';
    
    /**
     * Debug
     *
     * @var array
     */
    protected static $debug;
    
    const slug = 'gf-tenstreet';
    const name = 'GF_TenStreet';
    
    /**
     * Constructor
     *
     * @return void
     */
    function __construct() {

        self::$plugin_path = plugin_dir_path( dirname( dirname( __FILE__ ) ) );
        
        self::$plugin_file = self::$plugin_path . '/gf_tenstreet.php';
        
        // Hook up to the init action
        add_action( 'init', array (
            &$this,
            'init_GF_TenStreet'
        ) );
        
        // Add class instance to Addon Filter
        add_filter( 'gf_tenstreet_class_instance', array (
            $this,
            'get_instance'
        ), 10, 1 );
    }
    
    /**
     * Get Instance of Class
     * 
     * @param string $class
     * @return GF_TenStreet
     */
    public function get_instance($class) {
        return $this;
    }
    
    /**
     * Load the required dependencies for this class.
     *
     * Include the following files that make up the plugin:
     *
     * - GF_TenStreet_EndPoint. EndPoint Handler for API Functionality.
     * - Admin_GF_TenStreet. Admin Page Functionality.
     * - Network_Admin_GF_TenStreet. Network Admin Page Functionality.
     * - Post_Type_GF_TenStreet. Reporting Post Type Functionality.
     * - GF_TenStreet_Addon. Gravity Forms Add-on Functionality
     * - Helpers. Helper Functions
     */
    private function load_dependencies_GF_TenStreet() {
        
        /**
         * The class responsible for defining admin functionality.
         */
        require_once self::$plugin_path . 'includes/classes/class.admin_gf_tenstreet.php';
        /**
         * The class responsible for defining network admin functionality.
         */
        require_once self::$plugin_path . 'includes/classes/class.network_admin_gf_tenstreet.php';
        /**
         * The class responsible for defining helper functionality.
         */
        require_once self::$plugin_path . 'includes/helpers/functions.php';
        /**
         * The class responsible for defining Reporting functionality.
         */
        require_once self::$plugin_path . 'includes/classes/class.post_type_gf_tenstreet.php';
        
        if ($this->is_plugin_activated()) {
            /**
             * Helper Class for XML transformations.
             */
            require_once self::$plugin_path . 'includes/helpers/class.ArrToXml.php';
            /**
             * The class responsible for defining Gravity Forms functionality.
             */
            require_once self::$plugin_path . 'includes/classes/class.gf_tenstreet_addon.php';
        }
    }
    
    /**
     * Runs when the plugin is initialized
     *
     * @return void
     */
    function init_GF_TenStreet() {
        // Load Dependencies
        $this->load_dependencies_GF_TenStreet();
        
        // Setup localization
        load_plugin_textdomain( self::slug, false, dirname( plugin_basename( __FILE__ ) ) . '/lang' );
        
        // Setup Custom Post Type
        $first_run = $this->get_first_run();
        $this->post_type = new Post_Type_GF_TenStreet( $first_run );
        
        // Load Assets
        if (is_admin()) {
            
            // Init Admin_GForms_TMP
            $this->admin_gf_tenstreet = new Admin_GF_TenStreet();
        } else {
            add_action( 'wp_loaded', array (
                &$this,
                'load_assets_GF_TenStreet'
            ), 100 );
        }
    }
    
    /**
     * Loads Assets.
     *
     * @return void
     */
    function load_assets_GF_TenStreet() {
        
        // this will run when on the frontend
        add_action( 'wp_print_scripts', array (
            &$this,
            'load_scripts_GF_TenStreet'
        ) );
    }
    
    /**
     * Load Front End CSS/JS
     *
     * @return void
     */
    function load_scripts_GF_TenStreet() {}
    
    /**
     * Check if Plugin is active (and authorized)
     *
     * @return boolean Returns whether plugin is active
     */
    public function is_plugin_activated() {
        $is_authorized = get_option( 'gf_tenstreet_active', false );
        
        return $is_authorized;
    }
    
    /**
     * Get TenStreet Service Name
     * 
     * @return string
     */
    public static function get_service_name() {
        return self::$service_name;
    }
    
    /**
     * Return Endpoint url
     * 
     * @param string $mode
     * 
     * @return string
     */
    public static function get_wsdl_endpoint($mode = 'PROD') {
        return self::$wsdl[$mode == 'PROD' ? 'PROD' : 'DEV'];
    }
    
    /**
     * Set First Run static variable to true
     *
     * @return void
     */
    public static function set_first_run() {
        update_option('gf_tenstreet_first_run', time());
    }
    
    /**
     * Get First Run static variable
     *
     * @return boolean
     */
    protected function get_first_run() {
        $first_run = get_option('gf_tenstreet_first_run', false);
        return $first_run ? false : true;
    }
    
}
// end class
